Use C++20 when targeting MSVC. (#476)
In Visual Studio 2026 18.6.0 / MSVC 19.51+, <experimental/coroutine> is deprecated in favor of C++20 coroutine support. When built with a verison older than that, <winrt/base.h> ends up including that header, which triggers:

C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\14.51.36231\include\experimental/coroutine(37): error C2338: static assertion failed: 'error STL1011: The /await compiler option, <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> are deprecated by Microsoft and will be REMOVED SOON. They are superseded by the C++20 <coroutine> and C++23 <generator> headers. You can define _SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS to suppress this error for now.'

Using '20 avoids this.